### ISSUE TITLE
Bad gateway on some nesdis.noaa.gov URLs

### ISSUE THREAD

**Issue by rkaiser0324** [lanceberc/ycwx#2]
Running `fetch.sh` I got this after a short while:

![image](https://user-images.githubusercontent.com/1090569/204331240-ca08e2d7-6c53-426c-b25e-e99c862e308a.png)

I also see intermittent timeouts, maybe this is to be expected:

![image](https://user-images.githubusercontent.com/1090569/204331732-c3a73f27-099e-4b5d-bed3-c7c605a6a4ab.png)

**Comment by lanceberc** [comment]
Yes, NOAA is having trouble with one of its image servers - it started on
Nov 17th. I've been in touch with a sys admin who says that they're working
on it.

**Comment by lanceberc** [comment]
NOAA rebooted one of their servers around the 23rd/24th which has improved availability quite a bit but there are still occasional issues. The fetch code retries some errors (like open and read timeouts) but assumes that others like gateway issues are fatal. Those files will be retried the next time the script runs so files bypassed on one run will eventually be fetched if they actually exist (sometimes they don't).

**Comment by lanceberc** [comment]
I haven't seen any fetch issues on either the yc or dev machines for several days since NOAA rebooted the image server and may have made other network changes. Either way, I don't think the problem is on this end.
