### ISSUE TITLE
cmovie.py errors out

### ISSUE THREAD

**Issue by rkaiser0324** [lanceberc/ycwx#3]
I am testing all the scripts in `crontab.txt` and this one fails:

![image](https://user-images.githubusercontent.com/1090569/204350792-529617d7-2734-4050-801b-c51d0c2447c1.png)

First I notice that `www/html/data/overlay/BayDelta` doesn't exist. I create it and then get another error.  So I checked to see if `sfcanalysis.py` is behaving properly.  It returns quickly. I set loglevel to `logging.DEBUG` and it shows "same content" - don't know if that's expected.  At any rate something seems to be failing silently.

**Comment by lanceberc** [comment]
The time-lapse generator errors out if there are no source files or if any sources are corrupted. The BayDelta overlays are created at the end of nesdis-fetch.py when it calls paccup_overlay.py if any images were fetched from the CONUS-West region.

If you set up fetch.sh to run periodically the error messages will eventually go away as images appear and are processed. The errors will reappear is there are no new images (NOAA repository unavailable or northing from the satellites) within the most recent window for each time-lapse (e.g. 1 hour for Bay/Delta, 12 hours for West Coast, and 8 days for Pacific).

I'll leave this open as a reminder to automate looking for corrupted source files which has happened occasionally.

**Comment by rkaiser0324** [comment]
So I didn't let `nesdis-fetch.sh` run all the way through (it had 3K images to get) so that makes sense. I will run `paccup_overlay.py` directly, and make sure I have the prereqs documented for that.

**Comment by lanceberc** [comment]
The latest nesdis-fetch.py takes a timeout parameter to keep from having too many replicas active when catching up from repository unavailability; it defaults to 5 minutes. I've thought about retrieving new images in reverse time order so the most valuable are retrieved first which would help your case of starting a new location from scratch.

**Comment by rkaiser0324** [comment]
Looks like you have a syntax error in `nesdis-fetch.py`.  I am using Python 3.6.

![image](https://user-images.githubusercontent.com/1090569/204393425-48d43bcd-bf79-4c6d-9538-b516fc3d2f57.png)

I'm not a Python guy but it looks like your error is here:

![image](https://user-images.githubusercontent.com/1090569/204393494-6c65c74a-adbe-4b30-93d8-92ac8786cf63.png)

**Comment by lanceberc** [comment]
Oops - that's a bug. Fixed.
